name: docker-publish

on:
  push:
    branches: [ main ]
    tags: [ "v*" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [alpine, slim]
        include:
          - variant: alpine
            dockerfile: Dockerfile.alpine
            tags: |
              lillevang/teamtopologies-feed:alpine
              lillevang/teamtopologies-feed:latest
          - variant: slim
            dockerfile: Dockerfile.slim
            tags: |
              lillevang/teamtopologies-feed:slim
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (${{ matrix.variant }})
        uses: docker/build-push-action@v6
        with:
          file: ${{ matrix.dockerfile }}
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ matrix.tags }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.url=https://hub.docker.com/r/lillevang/teamtopologies-feed
            org.opencontainers.image.title=teamtopologies-feed
            org.opencontainers.image.description=Unofficial RSS feed for Team Topologies
